[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn run:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 