services:
  - type: web
    name: chatbot-platform
    env: python
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
    autoDeploy: true

databases:
  - name: chatbot-db
    databaseName: chatbot_platform
    user: chatbot_user
    plan: free 